Add editorconfig file and set rules
gmoraleslondono/retro-calculator pull request #20
Opened 2020-09-16 13:18 UTC by gmoraleslondono

Closes #15

2020-09-17 14:46 UTC, techeverri requested changes
I'd suggest:
- removing all the comments and
- sorting alphabetically the properties under the `[*]` (all files) section

2020-09-17 14:46 UTC, techeverri commented on .editorconfig
> +charset = utf-8
`charset` should be under the `[*]` (all files) section

2020-09-17 14:46 UTC, techeverri commented on .editorconfig
> +# Set default charset
Please remove example comment

2020-09-17 14:46 UTC, techeverri commented on .editorconfig
> +indent_size = 2
Move under the `[*]` (all files) section

2020-09-19 06:34 UTC, gmoraleslondono commented
Thank you! I did the changes

2020-09-19 10:33 UTC, techeverri reviewed
Does any of the properties conflict with Prettier? :thinking:

2020-09-22 21:42 UTC, techeverri approved these changes
Good job! 👍

2020-09-22 21:43 UTC, techeverri commented
In case there is any conflict between Prettier and the EditorConfig we can fix it later in a separate pull request

2020-09-22 21:51 UTC, gmoraleslondono commented
I checked and it doesn't have conflicts with prettier.

2020-09-22 21:51 UTC, merged